"""first migration

Revision ID: 917cac5c743b
Revises: 
Create Date: 2019-09-14 16:30:43.514601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917cac5c743b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychiatrist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychiatrist_email'), 'psychiatrist', ['email'], unique=True)
    op.create_index(op.f('ix_psychiatrist_username'), 'psychiatrist', ['username'], unique=True)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('psychiatrist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['psychiatrist_id'], ['psychiatrist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_email'), 'patient', ['email'], unique=True)
    op.create_index(op.f('ix_patient_username'), 'patient', ['username'], unique=True)
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary')
    op.drop_index(op.f('ix_patient_username'), table_name='patient')
    op.drop_index(op.f('ix_patient_email'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_psychiatrist_username'), table_name='psychiatrist')
    op.drop_index(op.f('ix_psychiatrist_email'), table_name='psychiatrist')
    op.drop_table('psychiatrist')
    # ### end Alembic commands ###
